name: queberry_test_pos_print_zoho_invoice
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.0.6 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  floor: ^1.4.2
  shared_preferences: ^2.2.0
  dio: any
  webview_flutter: ^4.2.2
  flutter_pretty_dio_logger: ^3.0.0
  flutter_email_sender: 5.1.0
  path_provider: ^2.0.5
  share: ^2.0.4
  http: any
  pdf: any
  esc_pos_utils: any
  esc_pos_printer: any
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  floor_generator: ^1.4.2
  build_runner: ^2.4.6
  flutter_test: 
    sdk: flutter



flutter: 
  uses-material-design: true
  assets:
    - assets/login.png
    - assets/signup.png

